Fixed VerifyError with ModifierNumbers
Fixed error with NumberObfuscation

Error: Unable to initialize main class gui.Main
Caused by: java.lang.VerifyError: get long/double overflows locals
Exception Details:
  Location: